export const TOGGLE_DRAWER = "TOGGLE_DRAWER";

export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_RECOMMENDATIONS = "FETCH_MOVIE_RECOMMENDATIONS";
export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_MOVIE_CREDITS = "FETCH_MOVIE_CREDITS";
export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_PERSON_MOVIE_CREDITS = "FETCH_PERSON_MOVIE_CREDITS";
export const FETCH_POPULAR_PEOPLE = "FETCH_POPULAR_PEOPLE";
export const FETCH_MOVIE_VIDEOS = "FETCH_MOVIE_VIDEOS";
export const FETCH_SEARCH = "FETCH_SEARCH";
export const FETCH_MOVIE_SEARCH = "FETCH_MOVIE_SEARCH";
export const FETCH_PERSON_SEARCH = "FETCH_PERSON_SEARCH";
export const FETCH_MOVIE_IMAGES = "FETCH_MOVIE_IMAGES";
export const FETCH_PERSON_IMAGES = "FETCH_PERSON_IMAGES";
