export const FETCH_MOVIE_CREDITS = "FETCH_MOVIE_CREDITS";
export const FETCH_PERSON_MOVIE_CREDITS = "FETCH_PERSON_MOVIE_CREDITS";
export const FETCH_MOVIE_VIDEOS = "FETCH_MOVIE_VIDEOS";
export const FETCH_SEARCH = "FETCH_SEARCH";
export const FETCH_MOVIE_SEARCH = "FETCH_MOVIE_SEARCH";
export const FETCH_PERSON_SEARCH = "FETCH_PERSON_SEARCH";
export const FETCH_MOVIE_IMAGES = "FETCH_MOVIE_IMAGES";
export const FETCH_PERSON_IMAGES = "FETCH_PERSON_IMAGES";
